import type { Pesewas } from '@plateraa/shared';
import { sql } from 'drizzle-orm';
import { bigint, customType, text, timestamp } from 'drizzle-orm/pg-core';
import { tenants } from './tenants.js';

/** Postgres 64-bit transaction id. Set by trigger on every insert and update; the sync cursor. */
const xid8 = customType<{ data: string; driverData: string }>({
  dataType: () => 'xid8',
});

/** ULID primary key, generated by the device or the server. */
export const id = () => text().primaryKey();

export const tenantId = () =>
  text()
    .notNull()
    .references(() => tenants.id);

/** Money in pesewas: BIGINT in Postgres, a branded safe integer in TypeScript. */
export const money = () => bigint({ mode: 'number' }).$type<Pesewas>();

export const timestamps = () => ({
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/** Columns every table the devices sync needs: soft delete so removals sync too, plus the cursor. */
export const syncColumns = () => ({
  deletedAt: timestamp({ withTimezone: true }),
  syncXid: xid8()
    .notNull()
    .default(sql`pg_current_xact_id()`),
});
