/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/onboarding/business": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OnboardingController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OnboardingController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DevicesController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/current/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DevicesController_roster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PinLoginController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StaffController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["StaffController_setPin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SyncController_push"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SyncController_pull"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto_Output: {
            /** @enum {string} */
            status: "ok";
        };
        CreateBusinessDto: {
            name: string;
            /** @enum {string} */
            vendorType: "CHOP_BAR" | "FAST_FOOD" | "CAFE_BAKERY" | "JUICE" | "CLOUD_KITCHEN" | "FOOD_TRUCK" | "OTHER";
        };
        BusinessCreatedDto_Output: {
            tenantId: string;
            slug: string;
            staffId: string;
        };
        BusinessDto_Output: {
            tenantId: string;
            name: string;
            slug: string;
            staffId: string;
            /** @enum {string} */
            role: "OWNER" | "MANAGER" | "STAFF" | "RIDER";
        };
        RegisterDeviceDto: {
            /** Format: ulid */
            tenantId: string;
            name: string;
            platform?: string;
            appVersion?: string;
        };
        RegisteredDeviceDto_Output: {
            deviceToken: string;
            device: {
                id: string;
                tenantId: string;
                locationId: string;
                name: string;
                code: string;
            };
        };
        RosterEntryDto_Output: {
            id: string;
            displayName: string;
            /** @enum {string} */
            role: "OWNER" | "MANAGER" | "STAFF" | "RIDER";
            pinVerifier: string[];
        };
        PinLoginDto: {
            /** Format: ulid */
            staffId: string;
            pin: string;
        };
        PinSessionDto_Output: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            staff: {
                id: string;
                displayName: string;
                /** @enum {string} */
                role: "OWNER" | "MANAGER" | "STAFF" | "RIDER";
            };
            capabilities: ("orders.take" | "orders.cancel" | "payments.record" | "shift.operate" | "shift.own_cash.view" | "stock.count" | "deliveries.update" | "refunds.record" | "payouts.record" | "discounts.apply" | "catalog.manage" | "staff.manage" | "expenses.manage" | "devices.manage" | "settings.manage" | "reports.revenue.view")[];
        };
        CreateStaffDto: {
            displayName: string;
            /** @enum {string} */
            role: "MANAGER" | "STAFF" | "RIDER";
            pin: string;
        };
        StaffCreatedDto_Output: {
            id: string;
            displayName: string;
            /** @enum {string} */
            role: "OWNER" | "MANAGER" | "STAFF" | "RIDER";
        };
        SetPinDto: {
            pin: string;
        };
        PushDto: {
            commands: ({
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.create";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                    displayNumber: string;
                    /** Format: date */
                    businessDate: string;
                    /** @enum {string} */
                    source: "POS" | "PHONE" | "STOREFRONT" | "BOLT_FOOD" | "CHOWDECK" | "OTHER";
                    /** @enum {string} */
                    type: "WALK_IN" | "PICKUP" | "DELIVERY";
                    externalReference?: string;
                    customer?: {
                        phone: string;
                        name?: string;
                    };
                    delivery?: {
                        address: string;
                        /** Format: ulid */
                        zoneId?: string;
                        fee: number;
                        /** @enum {string} */
                        feeCollectedBy?: "VENDOR" | "RIDER";
                    };
                    note?: string;
                    lines: {
                        /** Format: ulid */
                        lineId: string;
                        /** Format: ulid */
                        itemId: string;
                        /** Format: ulid */
                        variantId?: string;
                        quantity: number;
                        unitPrice: number;
                        modifiers?: {
                            /** Format: ulid */
                            modifierId: string;
                            unitPriceDelta: number;
                            quantity: number;
                        }[];
                        note?: string;
                    }[];
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.update_items";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                    lines: {
                        /** Format: ulid */
                        lineId: string;
                        /** Format: ulid */
                        itemId: string;
                        /** Format: ulid */
                        variantId?: string;
                        quantity: number;
                        unitPrice: number;
                        modifiers?: {
                            /** Format: ulid */
                            modifierId: string;
                            unitPriceDelta: number;
                            quantity: number;
                        }[];
                        note?: string;
                    }[];
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.set_status";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                    /** @enum {string} */
                    status: "CONFIRMED" | "PREPARING" | "READY" | "OUT_FOR_DELIVERY" | "COMPLETED";
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.hold";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.resume";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "order.cancel";
                payload: {
                    /** Format: ulid */
                    orderId: string;
                    reason: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "payment.record_cash";
                payload: {
                    /** Format: ulid */
                    paymentId: string;
                    /** Format: ulid */
                    orderId: string;
                    /** Format: ulid */
                    shiftId: string;
                    amount: number;
                    tendered?: number;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "payment.record_platform";
                payload: {
                    /** Format: ulid */
                    paymentId: string;
                    /** Format: ulid */
                    orderId: string;
                    amount: number;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "shift.open";
                payload: {
                    /** Format: ulid */
                    shiftId: string;
                    float: number;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "shift.cash_movement";
                payload: {
                    /** Format: ulid */
                    movementId: string;
                    /** Format: ulid */
                    shiftId: string;
                    /** @enum {string} */
                    type: "DROP" | "PAY_IN";
                    amount: number;
                    note?: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "shift.close";
                payload: {
                    /** Format: ulid */
                    shiftId: string;
                    counted: number;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "item.set_sold_out";
                payload: {
                    /** Format: ulid */
                    itemId: string;
                    soldOut: boolean;
                    /** Format: date */
                    businessDate: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "stock.prep_count";
                payload: {
                    /** Format: ulid */
                    movementId: string;
                    /** Format: ulid */
                    stockItemId: string;
                    quantity: number;
                    /** Format: date */
                    businessDate: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "stock.raw_count";
                payload: {
                    /** Format: ulid */
                    movementId: string;
                    /** Format: ulid */
                    stockItemId: string;
                    counted: number;
                    /** Format: date */
                    businessDate: string;
                };
            } | {
                /** Format: ulid */
                id: string;
                deviceSeq: number;
                /** Format: date-time */
                deviceTs: string;
                /** Format: ulid */
                staffId: string;
                /** @enum {string} */
                type: "customer.upsert";
                payload: {
                    /** Format: ulid */
                    customerId: string;
                    phone: string;
                    name?: string;
                    notes?: string;
                };
            })[];
        };
        PushResponseDto_Output: {
            results: ({
                id: string;
                /** @enum {string} */
                status: "APPLIED";
                result: {
                    [key: string]: unknown;
                };
            } | {
                id: string;
                /** @enum {string} */
                status: "REJECTED" | "RETRY";
                error: {
                    code: string;
                    message: string;
                };
            })[];
        };
        PullResponseDto_Output: {
            cursor: string;
            changes: {
                [key: string]: {
                    [key: string]: unknown;
                }[];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto_Output"];
                };
            };
        };
    };
    OnboardingController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBusinessDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessCreatedDto_Output"];
                };
            };
        };
    };
    OnboardingController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDto_Output"][];
                };
            };
        };
    };
    DevicesController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisteredDeviceDto_Output"];
                };
            };
        };
    };
    DevicesController_roster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntryDto_Output"][];
                };
            };
        };
    };
    PinLoginController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinLoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PinSessionDto_Output"];
                };
            };
        };
    };
    StaffController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStaffDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffCreatedDto_Output"];
                };
            };
        };
    };
    StaffController_setPin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPinDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SyncController_push: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushResponseDto_Output"];
                };
            };
        };
    };
    SyncController_pull: {
        parameters: {
            query?: {
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PullResponseDto_Output"];
                };
            };
        };
    };
}
